### PR TITLE
Sourcemap paths seem to be relative now?

### PR DESCRIPTION
**Pull request by Keats**
At least the test still pass and paths looks the same with and without the relative fudge.
Sourcemaps are completely wonky though and do not point at the right thing

Also removes jshint since it's using eslint now

### CODE REVIEW

**Comment by Keats** [comment]
@lmartins this is a wip, couldn't find a way to fix the sourcemaps but it seems that the paths are now relative so some code *might* be unnecessary

If the imports are not correct for gulp-sourcemaps, we'll need failing tests

**Comment by Snugug** [comment]
Bah, sorry, I messed this up when I was trying to fix the error logging. 

Have we tracked down if this is a `libsass` sourcemap issue or ` gulp-sourcemaps` sourcemap issue?

**Comment by Keats** [comment]
Not sure yet, I have to work right now so i'll do some digging sometimes tonight

**Comment by Snugug** [comment]
@Keats I'm working on this now.

**Comment by Snugug** [comment]
@lmartins So I believe I've isolated this.

I ran a test using the [Watson Design Library](https://github.com/IBM-Watson/design-library) Sass structure (fairly complex, lots of imports, some Bower stuff) as well as the code provided by @lmartins. I tested using both `node-sass` and the 2.x branch of `gulp-sass`. With both tests, with both compilers, source maps are built 100% correctly, which is awesome! So I started to investigate further.

It appears as if `gulp-autoprefixer` is a terrible terrible human being. and the culprit of our woes. Piping the output from `gulp-sass` to `gulp-autoprefixer` both destroyed most Sass file links, and the ones that somehow survived pointed to drastically wrong files. 

Now, that's not to say all's 100% perfect, but what isn't isn't on our side. While all of the line numbers for selectors resolve correctly, there are some instances where trying to jump to where a property's value comes from isn't correct, but it isn't correct (consistently) between our Gulp plugin and `node-sass`, which actually leads me to believe it's a Libsass problem, but IMO that's a much smaller problem.

**Comment by Snugug** [comment]
With all of that said, I've got the merge conflict dealt with manually and am going to push that.

**Comment by lmartins** [comment]
@Snugug Is your code in the current v2.x branch?
I just did a quick test, after removing autoprefixer and it still gives me skewed line numbers in source maps.

**Comment by Snugug** [comment]
Yup I did.

Can you see if you can pair down where the issue exists? I was looking at items that were higher up in the CSS source order than those at the bottom, but without having a more clear idea as to where the line numbering starts to break down it's very hard to debug this. For everything I looked at it appeared to be fine. Keep in mind that the line numbers are the start of a selector chain, not the position in a selector chain (for instance, if you have a reset whose selectors are on new lines, they all will point to the first selector).

@lmartins Can you see if you're getting the same issues with just raw `node-sass`? Having worked through this, I'm fairly confident it's not a `gulp-sass` issue and is probably a `node-sass` issue or even `libsass` issue. I can read through the `gulp-sourcemaps` source code, but I'm pretty sure it just collects the map stuff.

**Comment by lmartins** [comment]
Sure, I'll rebuild the Sass file step-by-step to see what might be having an influence in the skewed results. Im aware the line number refer to the selector and not to the rule itself, but towards the end of the file the "offset" is way off, sometimes giving different source-files.
I'll look further into this and let you know once I get to any conclusion.

**Comment by Snugug** [comment]
@lmartins This appears to be an upstream issue with `libsass` #113

**Comment by lmartins** [comment]
@Snugug Thanks, I haven't had the chance to rebuild the project yet but I hope to be able to do it later today.

**Comment by trichask** [comment]
@Snugug, @lmartins I removed gulp-autoprefixer and then the results were okay. Are you sure you still got messy results without autoprefixer?

**Pull request merged**
