### PR TITLE
Updated third party libs to add support for Node v8

### PR DESCRIPTION
**Pull request by flekschas**
Updated all third party dependencies. Adjusted tests to run with latest version of `gulp-tap`.

### CODE REVIEW

**Comment by xzyfer** [comment]
This will almost certainly break older node versions. Also the node-sass is not necessary.

**Comment by flekschas** [comment]
@xzyfer I am curious: can you post an example how you get the current version run in Node v8 without node-sass? Thanks

**Comment by xzyfer** [comment]
I'm on my phone. Check the the multiple duplicate issues for thorough
explanations.

**Comment by flekschas** [comment]
ok, never mind

**Pull request closed without merging**
