### PR TITLE
Modify sourcemap paths of imported files

### LINKED ISSUE #319: @imported files not given correct path or content in source map when a base is specified
Given a file *client/style/sass/aboutus.scss* : 
```
@import "base";

#aboutus-container {
	padding: 60px 15px 40px 15px;
	background-color: $gray;
    color: $charcoal;
    font-size: 16px;
}
```

and a file *client/style/sass/base.scss* : 
```
$teal: #0bbbd4;

$easternBlue: #ff9494;
$veryLightGray: #f6f6f6;
$lightGray: #F0F0F0;
$gray: #e9e9e9;
$mediumGray: #cccccc;
$charcoal: #5d5d5d;
$darkCharcoal: #393939; 
$neonGreen: #1fdd7c;
$warningOrange: #ff9900;
$pink: #ff9494;
$easternBlue: #008d9e;

$arrowSize: 7px;
...
```
The result of piping *client/style/sass/aboutus.scss* with a base: client, results in a source map that correctly references *client/style/sass/aboutus.scss*, but *client/style/sass/base.scss* is only referenced as *base.scss* without any content.

### PR DESCRIPTION
**Pull request by martinoconnor**
Modify sourcemap paths of imported files relative to file.base instead of relative to file, if a different base is specified. Resolves #319

### CODE REVIEW

**Comment by martinoconnor** [comment]
Possibly resolves #300 also.

**Comment by martinoconnor** [comment]
Used path.sep to reference the platform specific separator.

**Comment by mariusGundersen** [comment]
What's the status of this? I came across this exact issue in our project, and after many hours I came up with a fix that looks a lot like this one. I can confirm that it will fix the issue in our project as well.

I think a more elegant solution is to use `Array#map` to fix the sources list, as it requires fewer variables. Something like this:

```js
        sassFileSrc = file.relative;
        sassMap.sources = sassMap.sources.map(function(f){
          return f == sassMapFile
            // Replace the stdin with the original file name
            ? sassFileSrc
            // Get the path relative to base, not the original file path
            : path.join(path.dirname(sassFileSrc), f);
        });
```

**Comment by dometec** [comment]
The PR works. Cloud you please accept this PR and release the new version?

Thanks
Domenico

**Comment by Keats** [comment]
lgtm, @Snugug ?

**Comment by Snugug** [comment]
Me to.

**Comment by mariusGundersen** [comment]
Great! Any chance you can push this to npm as v2.0.5?

**Comment by glen-84** [comment]
:+1:

**Pull request merged**
