### PR TITLE
Update node-sass to 2.0.1

### PR DESCRIPTION
**Pull request by mdunisch**
Fix https://github.com/dlmanning/gulp-sass/issues/189 (Gulp-Sass won't work in latest nodejs 0.12.)

### CODE REVIEW

**Comment by dlmanning** [comment]
Tests are failing

**Comment by mdunisch** [comment]
Yes maybe a update of the tests are also necessary. But it gulp-sass itselfs works well in our develop with node-sass 2.0.1

**Comment by dlmanning** [comment]
No, it's #190. I'll fix it when I get to work in a couple hours

**Comment by austinpray** [comment]
Thanks guys

**Comment by mdunisch** [comment]
Fixed in https://github.com/dlmanning/gulp-sass/commit/314ce5c1594e541a55e5c5009fb0733c45226567

**Pull request closed without merging**
