### PR TITLE
2.x datastream

### LINKED ISSUE #158: gulp-sass discards changes from earlier in the pipeline when generating source maps
I believe there's a serious flaw in this plugin with the logic around `file.sourceMap` and `opts.sourceComments`. It results in node-sass attemping to re-read the file from disk, which discards changes from earlier in the gulp pipeline, and if an earlier change is a rename (e.g. with gulp-rename) it results in node-sass attemping to read a file which either doesn't exist or is the wrong file. Here are a couple of simple examples:

Given:

Gulp 3.8.10, gulp-sass 1.2.4, Ubuntu 12.

```js
var
  gulp = require('gulp'),
  sourcemaps = require('gulp-sourcemaps'),
  rename = require('gulp-rename'),
  sass = require('gulp-sass'),
  through = require('through2');
```

This (rename):
```js
gulp.task('default', function () {
  return gulp.src('./src/x.scss')
    .pipe(rename('y.scss'))
    .pipe(sourcemaps.init())
      .pipe(sass())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('./dist'));
});
```

Results in:
```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Error: File to read not found or unreadable: src/y.scss
```

And here is an example with a simple plugin that changes file contents (prepends a comment):

```js
var prefix = function () {
  var prefix = new Buffer("\n/* Added dynamically */\n", 'utf-8');

  return through.obj(function (file, enc, cb) {
    file.contents = Buffer.concat([prefix, file.contents]);
    this.push(file);
    cb();
  })
};

gulp.task('default', function () {
  return gulp.src('./src/x.scss')
    .pipe(prefix())
    .pipe(sourcemaps.init())
      .pipe(sass())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('./dist'));
});
```

This results in the changes from the prefix plugin being discarded.

This means that the changes proposed in [Consistent file handling #66](https://github.com/dlmanning/gulp-sass/pull/66) should not be accepted -- things need to go the other way.

If we're on the same page about this, I may work on a pull request.

### PR DESCRIPTION
**Pull request by Snugug**
Reroll of #225

* Passes file as data instead of passing file name
* Updates error message handling to show real file name instead of `stdin`
* Reimplements `includePaths` handling so we can pass file data directly
* Massages source maps to replace `stdin` and `stdout` with the right file names
* Resolves #158, #202

Do we think we should have tests specifically for the issues going on in there? I've done some basic tests to determine if it works, but nothing more in-depth.

### CODE REVIEW

**Comment by Keats** [comment]
lgtm, an opinion @dlmanning ?

**Comment by Snugug** [comment]
@dlmanning Once we get this merged in, I think we should release a beta, maybe bump `node-sass` to `beta` in `package.json`.

**Comment by dlmanning** [comment]
:+1: I'll publish a beta

**Comment by dlmanning** [comment]
@Snugug @Keats Should be able to install the alpha release now with `npm install gulp-sass@next`

**Pull request merged**
