### PR TITLE
changed node-sass version

### PR DESCRIPTION
**Pull request by morseltech**
tests pass

### CODE REVIEW

**Comment by xzyfer** [comment]
`^3.4.2` includes 3.10.1

https://github.com/npm/node-semver#caret-ranges-123-025-004

**Comment by morseltech** [comment]
But the last release is only 2.3.2 how can I get 3.4.2?

**Comment by morseltech** [comment]
Sorry I'm an idiot!

**Comment by morseltech** [comment]
Please forgive me!

**Pull request closed without merging**
