### PR TITLE
Merge 2.x into Master

### LINKED ISSUE #247: Release 2.0.0
Tracking sass/node-sass#904

- [x] Resolve [outstanding questions](https://github.com/dlmanning/gulp-sass/issues?q=is%3Aopen+milestone%3A2.0.0+label%3Aquestion)
- [x] Resolve [outstanding bugs](https://github.com/dlmanning/gulp-sass/issues?q=is%3Aopen+milestone%3A2.0.0+label%3Abug)
- [x] Resolve [outstanding enhancements](https://github.com/dlmanning/gulp-sass/issues?q=is%3Aopen+milestone%3A2.0.0+label%3Aenhancement)
- [x] Determine if [issues with no milestones](https://github.com/dlmanning/gulp-sass/issues?q=is%3Aopen+no%3Amilestone) should be included for 2.0.0 release
- [x] Bump Node Sass version to 3.0.0 (#253)
- [x] Add Contributing guidelines (#248)

### PR DESCRIPTION
**Pull request by Snugug**
This will merge 2.x into Master, paving the cowpaths for a rolled release.

Resolves #247

:shipit:

### CODE REVIEW

**Comment by xzyfer** [comment]
Oh hello there @Snugug :eyes:  let me return the favour :eyes:

**Comment by Snugug** [comment]
HI @xzyfer!

:eyes: :eyes: :eyes:

**Comment by Snugug** [comment]
Hey look! Greens! @dlmanning @Keats Can we get this merged in so we can get this out the door today? I'd love to release this on the same day (within a few hours?) of the 3.0 release

**Comment by Keats** [comment]
I'm going to write an article about the new stuff in gulp-sass 2 / libsass, hopefully done by tonight.
Caught me a bit off guard, didn't expect node-sass to be released that fast!
congrats @xzyfer

**Comment by xzyfer** [comment]
Thanks all, y'all rock!

**Comment by Snugug** [comment]
Wahoo! 
Sounds good @Keats!

@dlmanning Can we get this rolled out? Or do we now have the ability to roll those?

**Comment by dlmanning** [comment]
@snugug Give me a couple hours and I'll publish the release. I'll also add you and @keats as contributors on npm. Thanks for the great work!

**Comment by xzyfer** [comment]
I look forward to checking my email in the morning :)

**Comment by dlmanning** [comment]
@snugug Give me a couple hours and I'll publish the release. I'll also add you and @keats as contributors on npm. Thanks for the great work!

**Comment by Snugug** [comment]
Sounds good, thanks and thanks!

**Comment by dlmanning** [comment]
Published. Sorry about the delay; it was a busy day. @Snugug, I've added you as a contributor on npm. @Keats, if you tell me your npm username I'll do the same for you.

**Comment by Keats** [comment]
I don't have a npm user and to be honest, can't be arsed to create one right now.
No worries about the contributor thingy

**Comment by Keats** [comment]
Here's the article https://blog.wearewizards.io/gulp-sass-v2-released
Let me know if i made mistakes

**Pull request merged**
