### PR TITLE
Rewrite gulp-sass to be a very light wrapper

### PR DESCRIPTION
**Pull request by Keats**
Simply pass everything to node-sass and just hand back the results to gulp.
Removed custom options like success/failure cb and sync rendering, anyone using those?

TODO:
 -  gulp-sourcemaps support + test

Feedback?

### CODE REVIEW

**Comment by Keats** [comment]
@lmartins @dlmanning @Snugug

**Comment by dlmanning** [comment]
The callbacks I'm meh on... I added them in response to specific requests I probably should've said 'no' too. There's a bit of logic in there about paths for imports and partials that was making behavior a little more intuitive that we probably don't want to break. And then of course there's sourcemaps, which you mentioned.

**Comment by lmartins** [comment]
I believe that pretty much goes with the Gulp philosophy of keeping plugins as light and focused as possible. 
Regarding sourcemaps, support for `gulp-sourcemaps` is really useful for enabling the possibility of using things like `gulp-autoprefixer`, as an users is something I've been anxiously waiting for. Anyway, seems that `node-sass` also have something built-in: https://github.com/sass/node-sass#sourcemap

**Comment by Snugug** [comment]
I'm going to look at this tomorrow

**Comment by Keats** [comment]
I'll add he sourcemaps but i'm not using them myself so I wanted to see if there's interest before looking at it

**Comment by lmartins** [comment]
Source-maps are really important. I know how much it hurt to leave them behind to be able to use Libsass.

**Comment by dlmanning** [comment]
yup, sourcemap support with gulp-sourcemaps is a necessity. You guys don't even want to see how many angry issues will get opened if you mess with sourcemaps.

**Comment by Snugug** [comment]
Pulled this in to the [2.x branch](https://github.com/dlmanning/gulp-sass/tree/2.x) so we can all work on it together.

**Comment by Keats** [comment]
Cheers, I'll add sourcemaps if i have time today, tomorrow otherwise

**Comment by Snugug** [comment]
I'm working on that right now.

**Comment by Keats** [comment]
cool !

**Comment by Snugug** [comment]
Sourcemap support plus tests in the 2.x branch. I'm going to introduce linting and then we can look at merging everything @Keats @dlmanning

**Comment by Snugug** [comment]
I'd also like to clean up some of the outstanding issues before merging anything in.

@dlmanning I assume our workflow is merge to `dev` first, then to `master`, or is `dev` not used?

**Comment by Keats** [comment]
for the sourcemap you could use this option https://github.com/sass/node-sass#omitsourcemapurl to remove the need for the hack.

What do you mean by linting, jshint?

**Comment by Snugug** [comment]
ESLint, yeah

Weird. I tried that earlier and it didn't work, but it clearly does right now. I'm going to switch.

**Comment by lmartins** [comment]
I've just tried the v2 branch on my project, source-maps running but im facing an old standing issue that im not sure where it comes from. 
The source-maps are generated, but the line-numbers are way off, and that offset seems to grow as the project itself grows. Its easy to miss on small project though.

I've tried with autoprefixer enabled and disabled but came to the same result.

Is there any additional test I should make?

I will be running this version in my work today and let you know if I find other issue.

**Comment by Snugug** [comment]
I'm curious if it's a `gulp-sourcemap` problem or a `libsass` issue.

**Comment by Keats** [comment]
Did you solve that issue there https://github.com/floridoo/gulp-sourcemaps/issues/88 @lmartins ?

**Comment by lmartins** [comment]
@Keats Sadly no, I haven't been using source-maps since then because of this problem.

**Comment by Keats** [comment]
Do you have an example projet somewhere to try to debug it? I'll have some time later today

**Comment by lmartins** [comment]
I working on a WP project, would the complete SCSS folder structure work for you?

**Comment by Keats** [comment]
yep would be enough thanks

**Comment by lmartins** [comment]
Here goes:
https://cloudup.com/ckafKPjHBwY

I've included my Gulp configuration just in case. If you end up using that please adjust the `gulp-sass` so that it also adds the folder `lib` to the sass paths. The reason for that folder is so I can have a shared codebase for all my projects.

**Comment by Snugug** [comment]
Linting's done! It's in place and all of our files are updated to pass linting.

**Comment by Snugug** [comment]
@Keats Can you update the 2.x branch's `CHANGELOG` to reflect the work you've done?

**Comment by Keats** [comment]
Yeah, I'm trying to locate the sourcemap issues first

**Comment by Keats** [comment]
I opened https://github.com/dlmanning/gulp-sass/pull/220 to track progress on gulp-sourcemap issues.

@lmartins any reason you're using includePath instead of having symlinks? Not related to any issue, just curious

**Comment by lmartins** [comment]
old habits I guess, Sass always had this feature so I got used to it.

**Comment by Keats** [comment]
Check 2.x branch to see progress on that

**Pull request closed without merging**
