### PR TITLE
Add tests for sass+scss syntax

### PR DESCRIPTION
**Pull request by Keats**

### CODE REVIEW

**Comment by Keats** [comment]
I didn't really expect it to work but it does, would that solve https://github.com/dlmanning/gulp-sass/issues/199 and https://github.com/dlmanning/gulp-sass/issues/180 ?

**Comment by Snugug** [comment]
I'm fairly confident we don't need this in the newest version of `node-sass`

**Comment by Keats** [comment]
Looks that way, just waiting to see if some people from those issues can make a failing test

**Comment by Snugug** [comment]
I'd add one more test (that I just tried and I know passes): one file type importing another.

**Comment by Keats** [comment]
i added the test, not getting feedback from the people that opened issues on that topic though

**Comment by Snugug** [comment]
I'm willing to bet we're going to get a merge conflict with this and #224 as I've got tests written for that as well. How should we go about resolving that?

**Comment by Keats** [comment]
merge yours first and i'll rebase mine

**Comment by Snugug** [comment]
Sounds good. I'll merge that now.

**Comment by Snugug** [comment]
@Keats Looks like this didn't blow up like I thought it was going to. Would you like to add Sass tests for sync, or should we merge this in now and I'll add those.

@dlmanning Once we merge this in, I think we should release a beta

**Comment by Keats** [comment]
I don't think it needs specific sync test for sass+scss, it's more of an implementation detail from libsass/node-sass

**Comment by Snugug** [comment]
Okay. I'm going to re-run Travis because that merge didn't seem to trigger it, and when it passes I'll merge it in.

**Comment by Snugug** [comment]
Okay, so the test have failed because `assert` is not defined. If you could fix that error. I'm happy to merge

**Comment by Nicholaiii** [comment]
I am using 2.3.2 and this does not work for me. As soon as I change sass syntax into scss syntax they compile fine, but it throws up everywhere when I used mixed files.

**Comment by xzyfer** [comment]
Try adding .sass when importing files with the indented syntax

**Comment by Nicholaiii** [comment]
I am specifying all the files with a glob-array of *.s*ss, so the full file name will resolve to .sass or .scss depending on file.

**Pull request merged**
