### PR TITLE
check contents length for empty file

### PR DESCRIPTION
**Pull request by aj0strow**
re: https://github.com/dlmanning/gulp-sass/issues/275

### CODE REVIEW

**Comment by Snugug** [comment]
Please follow our [Contributing Guidelines](https://github.com/dlmanning/gulp-sass/blob/master/CONTRIBUTING.md) if you wish to contribute to Gulp Sass.

If this PR isn't updated to follow our contributing guidelines, I will close it until it is re-submitted following our requirements

**Comment by aj0strow** [comment]
I had the same issue as #275 and a bit of time, so fixed it. I find the guideline indulgent for a gulp plugin, do what you like.

**Comment by aj0strow** [comment]
"if someone is willing to do a PR with a test + fix i'll merge"

**Comment by mkoryak** [comment]
+1 this bug blew up our styles in prod for a few hours

**Comment by kashyapmukkamala** [comment]
+1 has this been fixed yet?

**Comment by mkoryak** [comment]
it would be great to get a new version on npm with this fix

**Pull request merged**
