### PR TITLE
Support for passing along `options.data` to `node-sass`

### PR DESCRIPTION
**Pull request by jonathanp**
I have a use case where I need to be able to pass along the option [`data`](https://www.npmjs.com/package/node-sass#data) to node-sass. This PR fixes this.

### CODE REVIEW

**Comment by jonathanp** [comment]
Hmm, those failing tests seems to not be related to this PR. The tests pass when `node-sass` v3.4.1 is used (as specified in `package.json`) but not in the latest v3.4.2.

**Comment by xzyfer** [comment]
I'm unclear what the usecase is here. Please elaborate.

**Comment by jonathanp** [comment]
I want to be able to use the `data` option that exists in node-sass, but through the gulp-sass plugin.

I think the unit test I added shows the use case pretty good; to be able to pass arbitrary strings from JS to Sass.

**Comment by jonnyscholes** [comment]
This PR would be great for us. We would like to be able to pass our static asset path (as defined in our case by a django instance) to sass. In our case we cannot use relative paths as the CSS is being inlined into the HTML after being compiled to CSS (for performance and IE9 file size issue reasons).

**Comment by xzyfer** [comment]
This feature has been discussed at length and reject until a valid use case can be proposed. Please read the discussion in https://github.com/dlmanning/gulp-sass/issues/302 for more context. 

If you believe you still believe you have use cases that doesn't violate the gulp semantics please leave a thorough description on that #302 and we'll reopen the discussion.

**Pull request closed without merging**
