### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by XhmikosR**
Nothing too fancy, but since `strip-ansi` has a security issue, we better force the update.

I'm going to keep this as draft, but ping me to update it before merging or a new release.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@xzyfer did you see my comments is #815? If you want to add a lock file I could add it here and adapt #813 too.

**Comment by xzyfer** [comment]
Adding a lock file would be preferable

**Comment by XhmikosR** [comment]
Done. After merging this, I'll update the other PRs to make use of `npm ci` and cache.

**Comment by xzyfer** [comment]
Thanks

**Pull request merged**
