### PR TITLE
Update node-sass to 4.12.0

### LINKED ISSUE #719: Update node-sass to 4.12.0 for NodeJS 12 support and to reverse a noisy CSS import deprecation warning
Please update node-sass to [4.11.0](https://github.com/sass/node-sass/releases). That version is currently in pre-release while 4.10.0 is `latest`, so I expect this issue to hang around for a bit. I'll have a small PR for this shortly.

### PR DESCRIPTION
**Pull request by simonua**
Fixes #719 

The same three tests fail pre- and post-change, so this PR does not appear to have any impact.

### CODE REVIEW

**Comment by chuanxd** [comment]
LGTM

**Comment by simonua** [comment]
@dlmanning, could this be merged, please? Thank you!

**Comment by pmrotule** [comment]
After running system updates on my MacBook Pro over the weekend (macOS Mojave version 10.14.3), I was having a Node Sass error coming from `gulp-sass` when I tried to start my web server: `Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (67)`. A good old `npm rebuild node-sass` wasn't helping this time. I also tried to delete _node_modules_ folder and re-install everything: didn't help either.

At the end, I realized that `gulp-sass` was not using the latest version of `node-sass` and using this fork, I was finally able to start my server as usual.

Thanks @simonua, can't wait to see this PR merged.

**Comment by xzyfer** [comment]
npm update node-sass is the non way of updating a transient dependency.

**Comment by simonua** [comment]
@pmrotule, you're welcome. Your situation applied to me similarly on the Windows side. =P

**Comment by jrgcubano** [comment]
hey @xzyfer really waiting for this! -> rgba, rgb and custom vars coming too

gulp-sass -> node-sass (even with 4.11 we need to wait until node-sass update to sass 3.56 with rgba vars) -> lib-sass

[issue in node-sass](https://github.com/sass/node-sass/issues/2610)

**Comment by danielpost** [comment]
Would be great if this could get merged so we can get rid of the CSS import warning.

**Comment by simonua** [comment]
@dlmanning, just a ping to float this back to the top of your inbox, good sir. It would be great if this could be merged and released, please.

Thank you!

**Comment by xzyfer** [comment]
npm update node-sass

**Comment by simonua** [comment]
I updated the PR with the latest version of `node-sass` released a few days ago that now supports NodeJS 12. @dlmanning, would be really, really great if this could be merged and released. Pretty please.

**Comment by hachibu** [comment]
My project really needs this as well. Thank you so much!

**Comment by TheDancingCode** [comment]
As @xzyfer already said twice, this PR isn't necessary. The solution is to simply `npm update node-sass` in your project.

**Comment by acdha** [comment]
@TheDancingCode: it’s better to have safe defaults than hope people find that default buried in an issue tracker after hitting a problem because they mistakenly assumed that `npm install gulp-sass` would do the right thing.

**Comment by simonua** [comment]
True, not necessary, and the suggestion helps, but I agree with good defaults and good package maintenance. Such is a team sport.

**Comment by uunbound** [comment]
If you are using `yarn` to install your npm packages, you can use [this solution](https://yarnpkg.com/en/docs/selective-version-resolutions/) to force installing node-sass v4.12.0.

**Comment by xzyfer** [comment]
This is not needed because of how SemVer works. You can always update the transient node-sass with `npm update node-sass` if you wish.

nodesource.com/blog/semver-tilde-and-caret

**Pull request closed without merging**
