### PR TITLE
Update Readme to clarify that `data` is not passed to node-sass

### PR DESCRIPTION
**Pull request by cheapsteak**

### CODE REVIEW

**Comment by xzyfer** [comment]
>Except for the `data` option which is used by gulp-sass internally. Using the `file` option is also unsupported and results in undefined behaviour that may change without notice.

**Comment by cheapsteak** [comment]
Updated phrasing per suggestion

**Comment by xzyfer** [comment]
Thank you @cheapsteak

**Comment by cheapsteak** [comment]
:)

**Pull request merged**
