### PR TITLE
WIP: update to node-sass version 2 beta

### PR DESCRIPTION
**Pull request by laurelnaiad**
This is a work in progress. Not to be merged as is....

To decide:

- pass through change in API such that success callback signature changes? If so, a breaking change notice and docs update are in order
- does this work with the multitude of options combinations possible?

### CODE REVIEW

**Comment by laurelnaiad** [comment]
(as being discussed in #147)

**Comment by laurelnaiad** [comment]
This turned out to be more basic than I was making it out to be in #147. I guess what's in this branch aside from the obvious move to object-based results from node-sass is a reduction of the logic that was being used to set parameters. If there are corner cases that break from this, I hope we can add tests to demo them and adjust accordingly. My hope is that the reason these reductions seem to work is that node-sass is handling the options combinations better now... we'll see.

**Comment by laurelnaiad** [comment]
This, in theory, also addresses what's intended in #154 to fix "#153 (and #148 ?)".

**Comment by bradcerasani** [comment]
@laurelnaiad Thanks for your work here - using your fork in a project and the added feature support in 2.0 beta is awesome.

To clarify, what needs to happen before this can be merged? Node-sass 2.0 stable looks to be [getting close](https://github.com/sass/node-sass/issues/602); if that's the blocker or if there's something else that needs attention, I'm happy to help where I can.

**Comment by laurelnaiad** [comment]
I don't know of anything in particular that needs to happen, aside from node-sass 2.0 being released (and being solid, which I know they're still working on), and the two bullet points in the comment (whether to expose API change to gulp-sass clients and "are all cases" handled question).

**Comment by jbrooksuk** [comment]
Is there any further progress on this? We're experiencing issues with our builds when we run on CentOS 6 and Debian Wheezy; https://github.com/cachethq/Cachet/issues/275

**Comment by awkaiser** [comment]
My team is also looking forward to the `node-sass` 2.0.0 merge for `gulp-sass`. Thanks @laurelnaiad!

**Comment by dlmanning** [comment]
Thanks @laurelnaiad! I'm gonna go ahead and publish this to latest on npm. Everyone cross their fingers that node-sass 2.0 is stable-ish.

**Pull request merged**
