### PR TITLE
Upgrade node-sass to beta 7 to fix solaris builds

### PR DESCRIPTION
**Pull request by SupremeTechnopriest**
as per https://github.com/sass/node-sass/issues/858

### CODE REVIEW

**Comment by Keats** [comment]
node-sass is currently at 3.1.2 so doing that would actually downgrade it.
If you npm install gulp-sass again you would get 3.1.2 which should work on solaris

**Comment by SupremeTechnopriest** [comment]
```
npm install gulp-sass --save-dev
npm WARN package.json msgpack-js-browser@0.1.4 'repositories' (plural) Not supported. Please pick one as the 'repository' field
-
> node-sass@3.1.2 install /root/LumeFX-App/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.1.2/sunos-x64-11_binding.node": HTTP error 404

> node-sass@3.1.2 postinstall /root/LumeFX-App/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

Building: /opt/local/bin/node node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
make: Entering directory `/root/LumeFX-App/node_modules/gulp-sass/node_modules/node-sass/build'
  CXX(target) Release/obj.target/libsass/src/libsass/ast.o
In file included from ../src/libsass/ast.hpp:34:0,
                 from ../src/libsass/ast.cpp:1:
../src/libsass/units.hpp:39:5: error: expected identifier before numeric constant
../src/libsass/units.hpp:39:5: error: expected '}' before numeric constant
../src/libsass/units.hpp:39:5: error: expected unqualified-id before numeric constant
../src/libsass/units.hpp:62:3: error: 'SassUnit' does not name a type
../src/libsass/units.hpp:63:30: error: 'SassUnit' was not declared in this scope
../src/libsass/units.hpp:63:30: note: suggested alternative:
../src/libsass/units.hpp:22:8: note:   'Sass::SassUnit'
../src/libsass/units.hpp:64:3: error: 'SassUnitType' does not name a type
../src/libsass/units.hpp:66:34: error: 'string' does not name a type
../src/libsass/units.hpp:66:40: error: ISO C++ forbids declaration of 'parameter' with no type [-fpermissive]
../src/libsass/units.hpp:66:49: error: 'string' does not name a type
../src/libsass/units.hpp:66:55: error: ISO C++ forbids declaration of 'parameter' with no type [-fpermissive]
../src/libsass/units.hpp:69:3: error: expected class-name before '{' token
../src/libsass/units.hpp:72:34: error: expected ')' before 'a'
../src/libsass/units.hpp:87:1: error: expected declaration before '}' token
make: *** [Release/obj.target/libsass/src/libsass/ast.o] Error 1
make: Leaving directory `/root/LumeFX-App/node_modules/gulp-sass/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/LumeFX-App/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System SunOS 5.11
gyp ERR! command "/opt/local/bin/node" "/root/LumeFX-App/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /root/LumeFX-App/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v0.10.32
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok
Build failed

npm ERR! node-sass@3.1.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.1.2 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! System SunOS 5.11
npm ERR! command "/opt/local/bin/node" "/opt/local/bin/npm" "install" "gulp-sass" "--save-dev"
npm ERR! cwd /root/LumeFX-App
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by SupremeTechnopriest** [comment]
Got a 404 on the node-sass binaries... When I `npm install node-sass` it breaks.  When I `npm install node-sass@beta` it does not.

**Comment by Keats** [comment]
That means node-sass doesn't have the binaries for solaris uploaded for some reason.
gulp-sass installs node-sass and node-sass will try to fetch binary by version/os

You can check https://github.com/sass/node-sass-binaries/issues/32

**Pull request closed without merging**
