### PR TITLE
Fix bug with includePaths

### PR DESCRIPTION
**Pull request by lynndylanhurley**
### problem
The value of `opts.includePaths` was somehow lost between files in the stream.

### fix
Create an array called `collectedIncludePaths` that retains all values of `opts.includePaths` that pass through the stream. The `collectedIncludePaths` is passed to node-sass as the `includePaths` value.

### etc.
The indentation was off so I normalized the file to use spaces. Let me know if this makes the PR too hard to read and I'll submit one that retains the original indentation.

### CODE REVIEW

**Comment by Keats** [comment]
gulp-sass v2 (branch 2.x) should solve that, if it's not please open a new issue

**Comment by booleanbetrayal** [comment]
@Keats / @dlmanning - looking forward to v2 for this fix. Any ETA, or is there a punch list to follow / contribute to?

**Comment by Keats** [comment]
It depends mostly on node-sass v3 being released (or very shortly after if there are some bugs)

**Comment by booleanbetrayal** [comment]
Thanks for the update!

**Pull request closed without merging**
