### PR TITLE
Travis CI: Tests fail on Node.js >= v12

### PR DESCRIPTION
**Pull request by cclauss**
https://travis-ci.org/github/dlmanning/gulp-sass/pull_requests

https://nodejs.org/api/fs.html

### CODE REVIEW

**Comment by xzyfer** [comment]
Thanks you but we should not fail on these node versions so instead we need to fix the root cause of the failures.

**Comment by cclauss** [comment]
> We need to fix the root cause of the failures.

Once that is done, the last 5 lines could be deleted.

**Comment by xzyfer** [comment]
Apologies I thought there were two separate PRs. Lets remove the allowed failures and I'll look into the build failures.

**Comment by xzyfer** [comment]
I can't reopen the PR because the branch has been deleted

**Comment by cclauss** [comment]
Recreated in #790

**Pull request closed without merging**
