### PR TITLE
Update node-sass 5.0.0

### PR DESCRIPTION
**Pull request by tanrax**

### CODE REVIEW

**Comment by rekmarks** [comment]
It would be positively astounding if this were merged 🙏

**Comment by rekmarks** [comment]
It'll probably require a major version bump of `gulp-sass` due to changes to permitted Node version, but it doesn't look like it'll require any code changes: https://github.com/sass/node-sass/releases/tag/v5.0.0

**Comment by tanrax** [comment]
Only with this small change it works for me

**Comment by sujeetkrjaiswal** [comment]
Why should gulp-sass needs a dependency on node-sass, given users can choose between node-sass and sass (dart-sass) as a compiler? An issue also has been opened for this: https://github.com/dlmanning/gulp-sass/issues/782

**Comment by C-Lodder** [comment]
Just make it a peerDependency so people have to manually install and manage the `node-sass` version.
Depending on a package that needs to ship new binaries for every Node.js version is a PITA

**Comment by rekmarks** [comment]
Signal boost: The problem hasn't gone away; I'd still love for this to happen.

**Comment by xzyfer** [comment]
Thanks all, close this to focus efforts on #802 which is more rounded at this point in time.

**Pull request closed without merging**
