### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by mimoduo**
Hey dlmanning,

https://github.com/dlmanning/gulp-sass/issues/741
Just going through and updating the dependencies.

Sincerely,
Bryan Stoner

### CODE REVIEW

**Comment by allan-simon** [comment]
awesome, it will permit us not to have to recompile node-sass everytime :)

**Comment by allan-simon** [comment]
strange enough the build is failing :/

**Comment by xzyfer** [comment]
This is far too aggressive of a change. 

It breaks backwards compatibility because some dependencies that were bumped have dropped Node < 6.

The bump of eslint has unnecessarily introduce new lint errors.

**Comment by xzyfer** [comment]
>awesome, it will permit us not to have to recompile node-sass everytime :)

You should never have to do to this. Just make sure you're running the latest node-sass. See `npm ls node-sass`.

**Comment by allan-simon** [comment]
> It breaks backwards compatibility because some dependencies that were bumped have dropped Node < 6.

Isn't node < 6 node more officially maintained ? (I think even node 8 is in maintenance mode ?)

**Comment by allan-simon** [comment]
> You should never have to do to this. Just make sure you're running the latest node-sass.

it's doing so because it does not find the good pre-built binary on github releases (the version of node-sass used by gulp-sass has no node-11 pre-built if I'm not mistaken )

**Comment by xzyfer** [comment]
gulp-sass will use the latest node-sass@4.x available at the time of
install because of the ^ in package.json

**Comment by LC43** [comment]
is there any progress on this? maybe skip eslint upgrade for now?

trying to clean a project of vulnerabilities and gulp-sass hits quite a few.

thanks for your work!

**Pull request closed without merging**
