### PR TITLE
Fixed sourcemaps with different file.base

### PR DESCRIPTION
**Pull request by TrySound**
Hi! Use sass and autoprefixer together on work. Need to fix ASAP.
Thanks!

### CODE REVIEW

**Comment by ai** [comment]
BTW, `file.path.split('/').pop()` is bad for Windows too

**Comment by Snugug** [comment]
@TrySound does this resolve the three linked issues?

**Comment by TrySound** [comment]
@Snugug Just https://github.com/dlmanning/gulp-sass/issues/276 and maybe https://github.com/dlmanning/gulp-sass/issues/276

**Comment by Snugug** [comment]
@TrySound #296 you mean?

**Comment by TrySound** [comment]
@Snugug Yes. https://github.com/dlmanning/gulp-sass/issues/296 resolved.

**Comment by Snugug** [comment]
:+1:

**Comment by Snugug** [comment]
Thank you for the PR!

**Comment by TrySound** [comment]
@Snugug Mapping still wrong. But I don't think it's gulp-sass's issue.

**Comment by TrySound** [comment]
@Snugug Don't forget to release and npm publish, please.

**Comment by Snugug** [comment]
Yup. Looking at the rest of the open PRs before I publish. It'll be in the next few hours.

**Comment by TrySound** [comment]
@Snugug you promised release.

**Comment by Snugug** [comment]
2.0.4 released.

**Comment by TrySound** [comment]
@Snugug Thanks!

**Comment by MaciejJanyska** [comment]
Thank you very much!

**Pull request merged**
